version: '3'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  plug-app:
    image: plug-app:latest
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/logs/nginx:/var/log/nginx
      - ./htmls/dist:/var/html
    depends_on:
      - plug-app
    ports:
      - 8080:80

volumes:
  db-data:
    driver: local
