version: '3'

services:
  postgresql:
    image: extvos/postgresql:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - ./data/postgres:/data

  plug-app:
    image: plug-app:latest
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/logs/nginx:/var/log/nginx
      - ./htmls/dist:/var/html
    depends_on:
      - plug-app
    ports:
      - 8080:80
