version: '3'

services:
  postgresql:
    image: extvos/postgresql:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - "./data/postgres:/var/lib/postgresql/data"

  plug-app:
    image: plug-app:latest
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/nginx.conf:/data/nginx/conf.d/default.conf
      - ./backend/public:/usr/share/nginx/html
    depends_on:
      - app
    ports:
      - 80:80